"""
SCRIPT SQL DDL (Oracle) - execute antes do programa:

CREATE TABLE monitoramento_tomate (
    id_monitoramento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    temperatura NUMBER(5,2) NOT NULL,
    umidade NUMBER(5,2) NOT NULL,
    classificacao_umidade VARCHAR2(20) NOT NULL,
    alerta_fungo CHAR(1) CHECK (alerta_fungo IN ('S','N')),
    fungo_confirmado CHAR(1) CHECK (fungo_confirmado IN ('S','N')),
    recomendacao VARCHAR2(200)
);
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, cast
import importlib
import json

try:
    oracledb: Any = cast(Any, importlib.import_module("oracledb"))
except ModuleNotFoundError:
    oracledb = None

# Tuplas (dados imutáveis) conforme requisito do Cap 4
PROBLEMAS_UMIDADE_BAIXA: tuple[str, ...] = (
    "Paralisação do crescimento",
    "Murcha e transpiração excessiva",
    "Aumento de pragas: mosca-branca e pulgão",
)

PROBLEMAS_UMIDADE_ALTA: tuple[str, ...] = (
    "Doenças fúngicas e bacterianas: requeima e pinta-preta",
    "Podridão apical (fundo preto)",
    "Rachaduras nos frutos",
    "Queda de flores",
    "Raízes sufocadas",
)

SINAIS_VISUAIS_FUNGO: tuple[str, ...] = (
    "Manchas escuras nas folhas",
    "Lesões circulares com halo",
    "Folhas com aspecto úmido e necrose",
    "Mofo visível em folhas ou caule",
)

RegistroMonitoramento = dict[str, Any]


def registrar_log(mensagem: str, arquivo_log: str = "operacoes.log") -> None:
    """Grava eventos em log TXT comum usando with open."""
    timestamp: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    linha: str = f"[{timestamp}] {mensagem}\n"
    with open(arquivo_log, "a", encoding="utf-8") as arquivo:
        arquivo.write(linha)


def ler_float_no_intervalo(prompt: str, minimo: float, maximo: float) -> float:
    """Leitura robusta de float com while + try/except ValueError."""
    while True:
        entrada: str = input(prompt).strip().replace(",", ".")
        try:
            valor: float = float(entrada)
            if valor < minimo or valor > maximo:
                print(f"Valor fora do intervalo permitido ({minimo} a {maximo}).")
                continue
            return valor
        except ValueError:
            print("Entrada inválida. Digite um número válido.")


def ler_inteiro_menu(prompt: str) -> int:
    """Leitura robusta para opções de menu."""
    while True:
        entrada: str = input(prompt).strip()
        try:
            return int(entrada)
        except ValueError:
            print("Opção inválida. Digite um número inteiro.")


def ler_sim_ou_nao(prompt: str) -> bool:
    """Leitura booleana para perguntas de confirmação."""
    while True:
        resposta: str = input(prompt).strip().lower()
        if resposta in ("s", "sim"):
            return True
        if resposta in ("n", "nao", "não"):
            return False
        print("Resposta inválida. Digite 's' para sim ou 'n' para não.")


def classificar_umidade(umidade: float) -> str:
    """Classifica umidade em baixa, adequada ou alta."""
    if umidade < 60.0:
        return "baixa"
    if umidade > 80.0:
        return "alta"
    return "adequada"


def calcular_risco_fungo(temperatura: float, umidade: float) -> bool:
    """Regra principal: umidade alta já ativa alerta. Temperatura refina contexto."""
    return umidade > 80.0 and 18.0 <= temperatura <= 32.0


def montar_recomendacao_fungo(fungo_confirmado: bool) -> str:
    """Define ação recomendada após verificação visual."""
    if fungo_confirmado:
        return "Aplicação do Fungicida X via pulverização"
    return "Sem confirmação de fungo. Manter monitoramento e prevenção."


def coletar_monitoramento(tabela_memoria: list[RegistroMonitoramento]) -> RegistroMonitoramento:
    """Cria um registro de monitoramento e adiciona na tabela em memória."""
    print("\n=== Novo Monitoramento da Cultura do Tomate ===")
    temperatura: float = ler_float_no_intervalo("Informe a temperatura (C): ", -10.0, 60.0)
    umidade: float = ler_float_no_intervalo("Informe a umidade relativa (%): ", 0.0, 100.0)

    classificacao: str = classificar_umidade(umidade)
    alerta_fungo: bool = calcular_risco_fungo(temperatura, umidade)
    fungo_confirmado: bool = False
    recomendacao: str = "Não aplicável"

    if classificacao == "baixa":
        print("\nUmidade BAIXA detectada. Problemas potenciais:")
        for problema in PROBLEMAS_UMIDADE_BAIXA:
            print(f"- {problema}")
        recomendacao = "Corrigir irrigação e elevar umidade do ambiente."

    elif classificacao == "alta":
        print("\nUmidade ALTA detectada. Problemas potenciais:")
        for problema in PROBLEMAS_UMIDADE_ALTA:
            print(f"- {problema}")

        print("\nSinais visuais de fungo para verificação em campo:")
        for sinal in SINAIS_VISUAIS_FUNGO:
            print(f"- {sinal}")

        print("\nALERTA DE FUNGO: realizar verificação visual obrigatória.")
        houve_verificacao: bool = ler_sim_ou_nao("Verificação visual realizada? (s/n): ")
        if houve_verificacao:
            fungo_confirmado = ler_sim_ou_nao("Fungo confirmado visualmente? (s/n): ")
        recomendacao = montar_recomendacao_fungo(fungo_confirmado)

    else:
        print("\nUmidade em faixa adequada para o tomateiro.")
        recomendacao = "Manter rotina preventiva e monitoramento diário."

    registro: RegistroMonitoramento = {
        "id_local": len(tabela_memoria) + 1,
        "data_hora": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "temperatura": temperatura,
        "umidade": umidade,
        "classificacao_umidade": classificacao,
        "alerta_fungo": alerta_fungo,
        "fungo_confirmado": fungo_confirmado,
        "recomendacao": recomendacao,
    }

    tabela_memoria.append(registro)
    registrar_log(f"Monitoramento local registrado: id_local={registro['id_local']}")
    print("\nMonitoramento registrado com sucesso na tabela de memória.")
    return registro


def listar_tabela_memoria(tabela_memoria: list[RegistroMonitoramento]) -> None:
    """Exibe os registros armazenados localmente."""
    print("\n=== Tabela de Memória (Lista dinâmica de dicionários) ===")
    if not tabela_memoria:
        print("Nenhum registro local encontrado.")
        return

    for registro in tabela_memoria:
        print("-" * 60)
        print(
            f"ID Local: {registro['id_local']} | Data/Hora: {registro['data_hora']}"
        )
        print(
            f"Temp: {registro['temperatura']} C | Umidade: {registro['umidade']}%"
        )
        print(f"Classificação: {registro['classificacao_umidade']}")
        print(f"Alerta fungo: {registro['alerta_fungo']}")
        print(f"Fungo confirmado: {registro['fungo_confirmado']}")
        print(f"Recomendacao: {registro['recomendacao']}")
    print("-" * 60)


def exportar_tabela_para_json(
    tabela_memoria: list[RegistroMonitoramento], caminho_arquivo: str = "monitoramentos.json"
) -> None:
    """Exporta a tabela local para JSON usando with open."""
    with open(caminho_arquivo, "w", encoding="utf-8") as arquivo:
        json.dump(tabela_memoria, arquivo, ensure_ascii=False, indent=4)

    registrar_log(f"Tabela de memória exportada para JSON: {caminho_arquivo}")
    print(f"Exportação concluída: {caminho_arquivo}")


def conectar_oracle() -> Any:
    """Conecta ao Oracle com tratamento de exceções."""
    if oracledb is None:
        print("Biblioteca 'oracledb' não instalada. Execute: pip install oracledb")
        registrar_log("Falha de conexão Oracle: biblioteca oracledb ausente")
        return None

    print("\n=== Conexão Oracle ===")
    usuario: str = input("Usuário: ").strip()
    senha: str = input("Senha: ").strip()
    dsn: str = input("DSN (ex: localhost:1521/XEPDB1): ").strip()

    try:
        conexao: Any = oracledb.connect(user=usuario, password=senha, dsn=dsn)
        print("Conexão Oracle realizada com sucesso.")
        registrar_log("Conexão Oracle estabelecida")
        return conexao
    except Exception as exc:
        print(f"Erro ao conectar no Oracle: {exc}")
        registrar_log(f"Erro de conexão Oracle: {exc}")
        return None


def inserir_monitoramento_oracle(conexao: Any, registro: RegistroMonitoramento) -> None:
    """CREATE no Oracle usando cursor, execute e commit."""
    sql: str = (
        "INSERT INTO monitoramento_tomate "
        "(data_hora, temperatura, umidade, classificacao_umidade, alerta_fungo, fungo_confirmado, recomendacao) "
        "VALUES (:1, :2, :3, :4, :5, :6, :7)"
    )

    alerta: str = "S" if registro["alerta_fungo"] else "N"
    fungo: str = "S" if registro["fungo_confirmado"] else "N"

    cursor = conexao.cursor()
    try:
        cursor.execute(
            sql,
            [
                datetime.strptime(registro["data_hora"], "%Y-%m-%d %H:%M:%S"),
                registro["temperatura"],
                registro["umidade"],
                registro["classificacao_umidade"],
                alerta,
                fungo,
                registro["recomendacao"],
            ],
        )
        conexao.commit()
        print("Registro inserido no Oracle com sucesso.")
        registrar_log("CREATE Oracle executado com sucesso")
    except Exception as exc:
        print(f"Erro ao inserir no Oracle: {exc}")
        registrar_log(f"Erro no CREATE Oracle: {exc}")
    finally:
        cursor.close()


def listar_monitoramentos_oracle(conexao: Any) -> None:
    """READ no Oracle."""
    sql: str = (
        "SELECT id_monitoramento, data_hora, temperatura, umidade, classificacao_umidade, "
        "alerta_fungo, fungo_confirmado, recomendacao "
        "FROM monitoramento_tomate ORDER BY id_monitoramento"
    )

    cursor = conexao.cursor()
    try:
        cursor.execute(sql)
        linhas: list[tuple[Any, ...]] = cursor.fetchall()
        if not linhas:
            print("Nenhum registro encontrado na tabela Oracle.")
            return

        print("\n=== Registros Oracle ===")
        for linha in linhas:
            print("-" * 60)
            print(
                f"ID: {linha[0]} | Data/Hora: {linha[1]} | Temp: {linha[2]} C | Umidade: {linha[3]}%"
            )
            print(
                f"Classificação: {linha[4]} | Alerta fungo: {linha[5]} | Fungo confirmado: {linha[6]}"
            )
            print(f"Recomendação: {linha[7]}")
        print("-" * 60)
        registrar_log("READ Oracle executado com sucesso")
    except Exception as exc:
        print(f"Erro ao listar Oracle: {exc}")
        registrar_log(f"Erro no READ Oracle: {exc}")
    finally:
        cursor.close()


def atualizar_recomendacao_oracle(conexao: Any) -> None:
    """UPDATE no Oracle."""
    id_monitoramento: int = ler_inteiro_menu("Informe o ID para atualizar recomendação: ")
    nova_recomendacao: str = input("Nova recomendação: ").strip()

    sql: str = "UPDATE monitoramento_tomate SET recomendacao = :1 WHERE id_monitoramento = :2"
    cursor = conexao.cursor()
    try:
        cursor.execute(sql, [nova_recomendacao, id_monitoramento])
        conexao.commit()
        if cursor.rowcount == 0:
            print("Nenhum registro atualizado (ID não encontrado).")
        else:
            print("Registro atualizado com sucesso.")
            registrar_log(f"UPDATE Oracle executado: id={id_monitoramento}")
    except Exception as exc:
        print(f"Erro ao atualizar Oracle: {exc}")
        registrar_log(f"Erro no UPDATE Oracle: {exc}")
    finally:
        cursor.close()


def excluir_monitoramento_oracle(conexao: Any) -> None:
    """DELETE no Oracle."""
    id_monitoramento: int = ler_inteiro_menu("Informe o ID para excluir: ")

    sql: str = "DELETE FROM monitoramento_tomate WHERE id_monitoramento = :1"
    cursor = conexao.cursor()
    try:
        cursor.execute(sql, [id_monitoramento])
        conexao.commit()
        if cursor.rowcount == 0:
            print("Nenhum registro excluído (ID não encontrado).")
        else:
            print("Registro excluído com sucesso.")
            registrar_log(f"DELETE Oracle executado: id={id_monitoramento}")
    except Exception as exc:
        print(f"Erro ao excluir Oracle: {exc}")
        registrar_log(f"Erro no DELETE Oracle: {exc}")
    finally:
        cursor.close()


def menu_crud_oracle(tabela_memoria: list[RegistroMonitoramento]) -> None:
    """Submenu CRUD do Oracle (Cap 6)."""
    conexao: Any = None

    while True:
        print("\n=== Menu Oracle CRUD ===")
        print("1. Conectar ao Oracle")
        print("2. CREATE - Inserir último monitoramento local")
        print("3. READ   - Listar monitoramentos")
        print("4. UPDATE - Atualizar recomendação")
        print("5. DELETE - Excluir monitoramento")
        print("6. Desconectar")
        print("0. Voltar ao menu principal")

        opcao: int = ler_inteiro_menu("Escolha: ")

        if opcao == 1:
            if conexao is not None:
                print("Já existe conexão ativa.")
            else:
                conexao = conectar_oracle()

        elif opcao == 2:
            if conexao is None:
                print("Conecte ao Oracle primeiro.")
                continue
            if not tabela_memoria:
                print("Não há monitoramentos locais para inserir.")
                continue
            inserir_monitoramento_oracle(conexao, tabela_memoria[-1])

        elif opcao == 3:
            if conexao is None:
                print("Conecte ao Oracle primeiro.")
                continue
            listar_monitoramentos_oracle(conexao)

        elif opcao == 4:
            if conexao is None:
                print("Conecte ao Oracle primeiro.")
                continue
            atualizar_recomendacao_oracle(conexao)

        elif opcao == 5:
            if conexao is None:
                print("Conecte ao Oracle primeiro.")
                continue
            excluir_monitoramento_oracle(conexao)

        elif opcao == 6:
            if conexao is None:
                print("Nenhuma conexão ativa para fechar.")
            else:
                conexao.close()
                conexao = None
                print("Conexão encerrada.")
                registrar_log("Conexão Oracle encerrada")

        elif opcao == 0:
            if conexao is not None:
                conexao.close()
                registrar_log("Conexão Oracle encerrada ao sair do submenu")
            break

        else:
            print("Opção inválida.")


def menu_principal() -> None:
    """Fluxo principal da aplicação CLI."""
    tabela_memoria: list[RegistroMonitoramento] = []
    registrar_log("Sistema iniciado")

    while True:
        print("\n=== Sistema de Monitoramento - Cultura do Tomate ===")
        print("1. Registrar novo monitoramento")
        print("2. Listar tabela de memória")
        print("3. Exportar tabela para JSON")
        print("4. Menu Oracle CRUD")
        print("0. Sair")

        opcao: int = ler_inteiro_menu("Escolha: ")

        if opcao == 1:
            coletar_monitoramento(tabela_memoria)
        elif opcao == 2:
            listar_tabela_memoria(tabela_memoria)
        elif opcao == 3:
            exportar_tabela_para_json(tabela_memoria)
        elif opcao == 4:
            menu_crud_oracle(tabela_memoria)
        elif opcao == 0:
            registrar_log("Sistema finalizado")
            print("Encerrando sistema. Até logo.")
            break
        else:
            print("Opção inválida. Tente novamente.")


if __name__ == "__main__":
    menu_principal()
